language: php

php:
- 7.1
- 7.2
- 7.3

before_script:
- composer self-update
- composer install --no-interaction

script:
- vendor/bin/phpunit --no-configuration tests --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash) -t 81240580-4954-4b59-920a-9953780414c0
